version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./db/postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
